name: neo_brutalism
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/refectco/neo_brutalism
homepage: https://refectco.com

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
